
// export const 
const types = {
    INIT_APPLICATION: 'INIT_APPLICATION',
    LOAD_CONFIG_PENDING: 'LOAD_CONFIG_PENDING',
    LOAD_CONFIG_SUCCESS: 'LOAD_CONFIG_SUCCESS',
    LOAD_CONFIG_FAILURE: 'LOAD_CONFIG_FAILURE'
}

export default types